//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OeilNoir {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OeilNoir.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Qualities&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Force&lt;/Name&gt;
        ///		&lt;Value&gt;8&lt;/Value&gt;
        ///		&lt;Sigle&gt;FO&lt;/Sigle&gt;
        ///		&lt;Color&gt;Orange&lt;/Color&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Courage&lt;/Name&gt;
        ///		&lt;Value&gt;8&lt;/Value&gt;
        ///		&lt;Sigle&gt;CO&lt;/Sigle&gt;
        ///		&lt;Color&gt;Rouge&lt;/Color&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Intuition&lt;/Name&gt;
        ///		&lt;Value&gt;8&lt;/Value&gt;
        ///		&lt;Sigle&gt;IU&lt;/Sigle&gt;
        ///		&lt;Color&gt;Vert&lt;/Color&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Intelligence&lt;/Name&gt;
        ///		&lt;Value&gt;8&lt;/Value&gt;
        ///		&lt;Sigle&gt;IN&lt;/Sigle&gt;
        ///		&lt;Color&gt;Violet&lt;/Color&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Agilité&lt;/Name&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Qualities {
            get {
                return ResourceManager.GetString("Qualities", resourceCulture);
            }
        }
    }
}
