//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OeilNoir {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OeilNoir.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Cultures&gt;
        ///  &lt;Culture&gt;
        ///    &lt;Name&gt;
        ///      Elfe des Bois
        ///    &lt;/Name&gt;
        ///    &lt;Pav&gt;
        ///      47
        ///    &lt;/Pav&gt;
        ///    &lt;Competences&gt;
        ///      &lt;Competence&gt;
        ///        &lt;Name&gt;
        ///          Chant
        ///        &lt;/Name&gt;
        ///        &lt;Value&gt;
        ///          2
        ///        &lt;/Value&gt;
        ///      &lt;/Competence&gt;
        ///    &lt;/Competences&gt;
        ///  &lt;/Culture&gt;
        ///&lt;/Cultures&gt;
        ///.
        /// </summary>
        public static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Peoples&gt;
        ///  &lt;People&gt;
        ///    &lt;Name&gt;
        ///      Humain
        ///    &lt;/Name&gt;
        ///    &lt;Cost&gt;
        ///      0
        ///    &lt;/Cost&gt;
        ///    &lt;EV&gt;
        ///      5
        ///    &lt;/EV&gt;
        ///    &lt;TM&gt;
        ///      -5
        ///    &lt;/TM&gt;
        ///    &lt;TP&gt;
        ///      -5
        ///    &lt;/TP&gt;
        ///    &lt;VI&gt;
        ///      8
        ///    &lt;/VI&gt;
        ///    &lt;CompulsoryQualities&gt;
        ///
        ///    &lt;/CompulsoryQualities&gt;
        ///    &lt;ChoosableQualities&gt;
        ///      &lt;Quality&gt;
        ///        &lt;Sigle&gt;FO&lt;/Sigle&gt;
        ///        &lt;Value&gt;1&lt;/Value&gt;
        ///      &lt;/Quality&gt;
        ///      &lt;Quality&gt;
        ///        &lt;Sigle&gt;CO&lt;/Sigle&gt;
        ///        &lt;Value&gt;1&lt;/Value&gt;
        ///      &lt;/Qual [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Peoples {
            get {
                return ResourceManager.GetString("Peoples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Qualities&gt;
        ///	&lt;Quality&gt;
        ///    &lt;Name&gt;Force&lt;/Name&gt;
        ///		&lt;Sigle&gt;FO&lt;/Sigle&gt;
        ///		&lt;Color&gt;Orange&lt;/Color&gt;
        ///    &lt;Value&gt;8&lt;/Value&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Courage&lt;/Name&gt;
        ///		&lt;Sigle&gt;CO&lt;/Sigle&gt;
        ///		&lt;Color&gt;Rouge&lt;/Color&gt;
        ///    &lt;Value&gt;8&lt;/Value&gt;
        ///  &lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Intuition&lt;/Name&gt;
        ///		&lt;Sigle&gt;IU&lt;/Sigle&gt;
        ///		&lt;Color&gt;Vert&lt;/Color&gt;
        ///    &lt;Value&gt;8&lt;/Value&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        ///		&lt;Name&gt;Intelligence&lt;/Name&gt;
        ///		&lt;Sigle&gt;IN&lt;/Sigle&gt;
        ///		&lt;Color&gt;Violet&lt;/Color&gt;
        ///    &lt;Value&gt;8&lt;/Value&gt;
        ///	&lt;/Quality&gt;
        ///	&lt;Quality&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Qualities {
            get {
                return ResourceManager.GetString("Qualities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;StartLevels&gt;
        ///  &lt;StartLevel&gt;
        ///    &lt;Pav&gt;
        ///      1000
        ///    &lt;/Pav&gt;
        ///    &lt;Ft&gt;
        ///      10
        ///    &lt;/Ft&gt;
        ///    &lt;MaxValComp&gt;
        ///      10
        ///    &lt;/MaxValComp&gt;
        ///    &lt;MaxValQual&gt;
        ///      13
        ///    &lt;/MaxValQual&gt;
        ///    &lt;Qp&gt;
        ///      98
        ///    &lt;/Qp&gt;
        ///    &lt;Spells&gt;
        ///      10
        ///    &lt;/Spells&gt;
        ///    &lt;SpellsHT&gt;
        ///      1
        ///    &lt;/SpellsHT&gt;
        ///    &lt;Name&gt;
        ///      Moyen
        ///    &lt;/Name&gt;
        ///  &lt;/StartLevel&gt;
        ///&lt;/StartLevels&gt;.
        /// </summary>
        public static string StartLevels {
            get {
                return ResourceManager.GetString("StartLevels", resourceCulture);
            }
        }
    }
}
